/*****************************************************************************
* Model: bwgpsrecorder.qm
* File:  qmcode/q3dsensor.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/3/3) .................................................................*/
#include "qp_port.h"
#include "qevents.h"
#include "bsp.h"
#include "type.h"

Q_DEFINE_THIS_MODULE("qsensors.c")

#define DETECTING_KEPT_AMOUNT  4 //检测累计次数：100次，共用时1S
#define TIMEOUT_DETECTING      (BSP_TICKS_PER_SEC >> 1) //检测周期
#define TIMEOUT_READ           (BSP_TICKS_PER_SEC / 10)  //检测周期, 100ms

///内部消息
enum {
    IN_SIG_DET_OK_SIG = 0,
    IN_SIG_DET_ERR_SIG,

};

/* Active object class -----------------------------------------------------*/
/* @(/1/2) .................................................................*/
typedef struct Q3DSensorTag {
/* protected: */
    QActive super;

/* public: */
    uint16_t x;
    uint16_t y;
    uint16_t z;
    uint16_t angX;
    uint16_t angY;
    uint16_t angZ;
    int16_t is_Ready;
    QTimeEvt m_Timer;
} Q3DSensor;

/* protected: */
static QState Q3DSensor_initial(Q3DSensor * const me, QEvt const * const e);
static QState Q3DSensor_detecting(Q3DSensor * const me, QEvt const * const e);
static QState Q3DSensor_error(Q3DSensor * const me, QEvt const * const e);
static QState Q3DSensor_ready(Q3DSensor * const me, QEvt const * const e);



/* Local objects -----------------------------------------------------------*/
static Q3DSensor l_Q3DSensor; /* the single instance of the Table active object */

/* Global-scope objects ----------------------------------------------------*/
QActive * const AO_3DSensor = &l_Q3DSensor.super; /* "opaque" AO pointer */

/*..........................................................................*/
/* @(/1/24) ................................................................*/
void Q3DSensor_ctor(void) {
    Q3DSensor *me = &l_Q3DSensor;
    QActive_ctor(&me->super, Q_STATE_CAST(&Q3DSensor_initial));
    QTimeEvt_ctor(&me->m_Timer, PER_SECOND_SIG);
}
/* @(/1/2) .................................................................*/
/* @(/1/2/8) ...............................................................*/
/* @(/1/2/8/0) */
static QState Q3DSensor_initial(Q3DSensor * const me, QEvt const * const e) {
    ADXL345_Init();
    return Q_TRAN(&Q3DSensor_detecting);
}
/* @(/1/2/8/1) .............................................................*/
static QState Q3DSensor_detecting(Q3DSensor * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* @(/1/2/8/1) */
        case Q_ENTRY_SIG: {
            me->is_Ready = ADXL345_Detecting();
            if(me->is_Ready == 0)
                QACTIVE_POST(AO_3DSensor, IN_SIG_DET_OK_SIG, NULL);
            else
                QACTIVE_POST(AO_3DSensor, IN_SIG_DET_ERR_SIG, NULL);

            status_ = Q_HANDLED();
            break;
        }
        /* @(/1/2/8/1/0) */
        case IN_SIG_DET_ERR_SIG: {
            status_ = Q_TRAN(&Q3DSensor_error);
            break;
        }
        /* @(/1/2/8/1/1) */
        case IN_SIG_DET_OK_SIG: {
            status_ = Q_TRAN(&Q3DSensor_ready);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/* @(/1/2/8/2) .............................................................*/
static QState Q3DSensor_error(Q3DSensor * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/* @(/1/2/8/3) .............................................................*/
static QState Q3DSensor_ready(Q3DSensor * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* @(/1/2/8/3) */
        case Q_ENTRY_SIG: {
            /* 使能秒定时器 */
            QTimeEvt_postEvery(&me->m_Timer, &me->super, TIMEOUT_READ);
            status_ = Q_HANDLED();
            break;
        }
        /* @(/1/2/8/3) */
        case Q_EXIT_SIG: {
            QTimeEvt_disarm(&me->m_Timer);
            status_ = Q_HANDLED();
            break;
        }
        /* @(/1/2/8/3/0) */
        case Q_TIMEOUT_SIG: {
            //读取X,Y,Z三个方向的加速度值
            ADXL345_Read_Average(&me->x,&me->y,&me->z,10);
            //得到角度值,并显示
            me->angX=ADXL345_Get_Angle(me->x,me->y,me->z,1);
            me->angY=ADXL345_Get_Angle(me->x,me->y,me->z,2);
            me->angZ=ADXL345_Get_Angle(me->x,me->y,me->z,0);
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

