/*****************************************************************************
* Model: bwgpsrecorder.qm
* File:  qmcode/qactiveobjs.h
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/3/0) .................................................................*/
#ifndef AOS_H
#define AOS_H

#include "qp_port.h"
#include "stm32f2xx.h"



/** 状态机定义 =====================================================*/

/* @(/1/21) ................................................................*/
void QGprs_ctor(void);

/* @(/1/22) ................................................................*/
void QGps_ctor(void);

/* @(/1/31) ................................................................*/
void QCAN_ctor(void);

/* @(/1/23) ................................................................*/
void QExtSignals_ctor(void);

/* @(/1/28) ................................................................*/
void QLCD_ctor(void);

/* @(/1/24) ................................................................*/
void Q3DSensor_ctor(void);

/* @(/1/25) ................................................................*/
void QVideo_ctor(void);

/* @(/1/27) ................................................................*/
void QSystick_ctor(void);

/* @(/1/26) ................................................................*/
void QUpgrade_ctor(void);

/* @(/1/30) ................................................................*/
void QTTS_ctor(void);

/* @(/1/32) ................................................................*/
void QACCDetector_ctor(void);

/* @(/1/26) ................................................................*/
void QUpgrade_ctor(void);

/* @(/1/35) ................................................................*/
void QRecorder_ctor(void);

/* @(/1/36) ................................................................*/
void QICcard_ctor(void);

/* @(/1/37) ................................................................*/
void QPrinter_ctor(void);

/* @(/1/38) ................................................................*/
void QIR_ctor(void);

/* @(/1/39) ................................................................*/
void QDigital_ctor(void);

/* @(/1/40) ................................................................*/
void QUSB_ctor(void);

/* @(/1/29) ................................................................*/
void QAudio_ctor(void);

/* @(/1/42) ................................................................*/
void QVDR_ctor(void);




/** 状态机声明 =====================================================*/

extern QActive * const AO_Gprs;
extern QActive * const AO_Gps;
extern QActive * const AO_Can;
extern QActive * const AO_ExtSignals;
extern QActive * const AO_LCD;
extern QActive * const AO_3DSensor;
extern QActive * const AO_Video;
extern QActive * const AO_Upgrade;
extern QActive * const AO_TTS;
extern QActive * const AO_ACCDetector;
extern QActive * const AO_Systick;
extern QActive * const AO_Upgrade;
extern QActive * const AO_Recorder;
extern QActive * const AO_ICCard;
extern QActive * const AO_Printer;
extern QActive * const AO_IR;
extern QActive * const AO_Digital;
extern QActive * const AO_USB;
extern QActive * const AO_Audio;
extern QActive * const AO_VDR;

#endif
