/*****************************************************************************
* Model: bwgpsrecorder.qm
* File:  qmcode/qaudio.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/3/6) .................................................................*/
#include "qp_port.h"
#include "qevents.h"
#include "bsp.h"
#include "type.h"

Q_DEFINE_THIS_MODULE("qaudio.c")



/* Active object class -----------------------------------------------------*/
/* @(/1/5) .................................................................*/
typedef struct QAudioTag {
/* protected: */
    QActive super;
} QAudio;

/* protected: */
static QState QAudio_initial(QAudio * const me, QEvt const * const e);
static QState QAudio_idle(QAudio * const me, QEvt const * const e);
static QState QAudio_busy(QAudio * const me, QEvt const * const e);



/* Local objects -----------------------------------------------------------*/
static QAudio l_Audio; /* the single instance of the Table active object */

/* Global-scope objects ----------------------------------------------------*/
QActive * const AO_Audio = &l_Audio.super; /* "opaque" AO pointer */

/*..........................................................................*/
/* @(/1/29) ................................................................*/
void QAudio_ctor(void) {
    QAudio *me = &l_Audio;
    QActive_ctor(&me->super, Q_STATE_CAST(&QAudio_initial));
}
/* @(/1/5) .................................................................*/
/* @(/1/5/0) ...............................................................*/
/* @(/1/5/0/0) */
static QState QAudio_initial(QAudio * const me, QEvt const * const e) {
    TTS_Init();
    return Q_TRAN(&QAudio_idle);
}
/* @(/1/5/0/1) .............................................................*/
static QState QAudio_idle(QAudio * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* @(/1/5/0/1/0) */
        case AUDIO_RECORD_START_SIG: {
            status_ = Q_TRAN(&QAudio_busy);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/* @(/1/5/0/2) .............................................................*/
static QState QAudio_busy(QAudio * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* @(/1/5/0/2/0) */
        case AUDIO_RECORD_STOP_SIG: {
            status_ = Q_TRAN(&QAudio_idle);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

