/*****************************************************************************
* Model: bwgpsrecorder.qm
* File:  qmcode/qdigital.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/3/18) ................................................................*/
#include "qp_port.h"
#include "qevents.h"
#include "bsp.h"
#include "utility.h"
#include "error.h"
#include "type.h"

Q_DEFINE_THIS_MODULE("qdigital.c")


/* Active object class -----------------------------------------------------*/
/* @(/1/17) ................................................................*/
typedef struct QDigitalTag {
/* protected: */
    QActive super;
} QDigital;

/* protected: */
static QState QDigital_initial(QDigital * const me, QEvt const * const e);
static QState QDigital_state1(QDigital * const me, QEvt const * const e);



/* Local objects -----------------------------------------------------------*/
static QDigital l_QDigital; /* the single instance of the Table active object */

/* Global-scope objects ----------------------------------------------------*/
QActive * const AO_Digital = &l_QDigital.super; /* "opaque" AO pointer */

/*..........................................................................*/
/* @(/1/39) ................................................................*/
void QDigital_ctor(void) {
    QDigital *me = &l_QDigital;
    QActive_ctor(&me->super, Q_STATE_CAST(&QDigital_initial));
}
/* @(/1/17) ................................................................*/
/* @(/1/17/0) ..............................................................*/
/* @(/1/17/0/0) */
static QState QDigital_initial(QDigital * const me, QEvt const * const e) {
    return Q_TRAN(&QDigital_state1);
}
/* @(/1/17/0/1) ............................................................*/
static QState QDigital_state1(QDigital * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

