/*****************************************************************************
* Model: bwgpsrecorder.qm
* File:  qmcode/qextsignals.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/3/1) .................................................................*/
#include "qp_port.h"
#include "qevents.h"
#include "bsp.h"
#include "type.h"

Q_DEFINE_THIS_MODULE("qextsignals.c")



/* Active object class -----------------------------------------------------*/
/* @(/1/0) .................................................................*/
typedef struct QExtSignalsTag {
/* protected: */
    QActive super;
} QExtSignals;

/* protected: */
static QState QExtSignals_initial(QExtSignals * const me, QEvt const * const e);
static QState QExtSignals_serving(QExtSignals * const me, QEvt const * const e);



/* Local objects -----------------------------------------------------------*/
static QExtSignals l_ExtSignals; /* the single instance of the Table active object */

/* Global-scope objects ----------------------------------------------------*/
QActive * const AO_ExtSignals = &l_ExtSignals.super; /* "opaque" AO pointer */

/*..........................................................................*/
/* @(/1/23) ................................................................*/
void QExtSignals_ctor(void) {
    QExtSignals *me = &l_ExtSignals;
    QActive_ctor(&me->super, Q_STATE_CAST(&QExtSignals_initial));
}
/* @(/1/0) .................................................................*/
/* @(/1/0/0) ...............................................................*/
/* @(/1/0/0/0) */
static QState QExtSignals_initial(QExtSignals * const me, QEvt const * const e) {
    return Q_TRAN(&QExtSignals_serving);
}
/* @(/1/0/0/1) .............................................................*/
static QState QExtSignals_serving(QExtSignals * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

