/*****************************************************************************
* Model: bwgpsrecorder.qm
* File:  qmcode/qIR.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/3/17) ................................................................*/
#include "qp_port.h"
#include "qevents.h"
#include "bsp.h"
#include "utility.h"
#include "error.h"
#include "type.h"

Q_DEFINE_THIS_MODULE("qIR.c")


/* Active object class -----------------------------------------------------*/
/* @(/1/16) ................................................................*/
typedef struct QIRTag {
/* protected: */
    QActive super;
} QIR;

/* protected: */
static QState QIR_initial(QIR * const me, QEvt const * const e);
static QState QIR_state1(QIR * const me, QEvt const * const e);



/* Local objects -----------------------------------------------------------*/
static QIR l_QIR; /* the single instance of the Table active object */

/* Global-scope objects ----------------------------------------------------*/
QActive * const AO_IR = &l_QIR.super; /* "opaque" AO pointer */

/*..........................................................................*/
/* @(/1/38) ................................................................*/
void QIR_ctor(void) {
    QIR *me = &l_QIR;
    QActive_ctor(&me->super, Q_STATE_CAST(&QIR_initial));

    //QTimeEvt_ctor(&me->m_Timer, Q_TIMEOUT_SIG);
}
/* @(/1/16) ................................................................*/
/* @(/1/16/0) ..............................................................*/
/* @(/1/16/0/0) */
static QState QIR_initial(QIR * const me, QEvt const * const e) {
    return Q_TRAN(&QIR_state1);
}
/* @(/1/16/0/1) ............................................................*/
static QState QIR_state1(QIR * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

