/*****************************************************************************
* Model: bwgpsrecorder.qm
* File:  qmcode/qsensors.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/3/3) .................................................................*/
#include "qp_port.h"
#include "qevents.h"
#include "bsp.h"
#include "type.h"

Q_DEFINE_THIS_MODULE("qsensors.c")

#define DETECTING_KEPT_AMOUNT  4 //检测累计次数：100次，共用时1S
#define TIMEOUT_DETECTING      (BSP_TICKS_PER_SEC >> 1) //检测周期

/* Active object class -----------------------------------------------------*/
/* @(/1/2) .................................................................*/
typedef struct QSensorsTag {
/* protected: */
    QActive super;
} QSensors;

/* protected: */
static QState QSensors_initial(QSensors * const me, QEvt const * const e);
static QState QSensors_state1(QSensors * const me, QEvt const * const e);



/* Local objects -----------------------------------------------------------*/
static QSensors l_Sensors; /* the single instance of the Table active object */

/* Global-scope objects ----------------------------------------------------*/
QActive * const AO_Sensors = &l_Sensors.super; /* "opaque" AO pointer */

/*..........................................................................*/
/* @(/1/24) ................................................................*/
void QSensors_ctor(void) {
    QSensors *me = &l_Sensors;
    QActive_ctor(&me->super, Q_STATE_CAST(&QSensors_initial));
}
/* @(/1/2) .................................................................*/
/* @(/1/2/0) ...............................................................*/
/* @(/1/2/0/0) */
static QState QSensors_initial(QSensors * const me, QEvt const * const e) {
    return Q_TRAN(&QSensors_state1);
}
/* @(/1/2/0/1) .............................................................*/
static QState QSensors_state1(QSensors * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

