/*****************************************************************************
* Model: bwgpsrecorder.qm
* File:  qmcode/qsystick.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/3/11) ................................................................*/
#include "qp_port.h"
#include "qevents.h"
#include "bsp.h"
#include "type.h"
#include "protocol.h"
#include "utility.h"
#include "error.h"

Q_DEFINE_THIS_MODULE("qsystick.c")

/* Active object class -----------------------------------------------------*/
/* @(/1/4) .................................................................*/
typedef struct QSystickTag {
/* protected: */
    QActive super;
} QSystick;

/* protected: */
static QState QSystick_initial(QSystick * const me, QEvt const * const e);
static QState QSystick_state1(QSystick * const me, QEvt const * const e);


/* Local objects -----------------------------------------------------------*/
static QSystick l_Systick; /* the single instance of the Table active object */

/* Global-scope objects ----------------------------------------------------*/
QActive * const AO_Systick = &l_Systick.super; /* "opaque" AO pointer */

/*..........................................................................*/
/* @(/1/27) ................................................................*/
void QSystick_ctor(void) {
    QSystick *me = &l_Systick;
    QActive_ctor(&me->super, Q_STATE_CAST(&QSystick_initial));
}
/* @(/1/4) .................................................................*/
/* @(/1/4/0) ...............................................................*/
/* @(/1/4/0/0) */
static QState QSystick_initial(QSystick * const me, QEvt const * const e) {
    return Q_TRAN(&QSystick_state1);
}
/* @(/1/4/0/1) .............................................................*/
static QState QSystick_state1(QSystick * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}


