/*****************************************************************************
* Model: bwgpsrecorder.qm
* File:  qmcode/qtts.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/3/7) .................................................................*/
#include "qp_port.h"
#include "qevents.h"
#include "bsp.h"
#include "type.h"

Q_DEFINE_THIS_MODULE("qtts.c")



/* Active object class -----------------------------------------------------*/
/* @(/1/6) .................................................................*/
typedef struct QTTSTag {
/* protected: */
    QActive super;
} QTTS;

/* protected: */
static QState QTTS_initial(QTTS * const me, QEvt const * const e);
static QState QTTS_normal(QTTS * const me, QEvt const * const e);
static QState QTTS_idle(QTTS * const me, QEvt const * const e);
static QState QTTS_busy(QTTS * const me, QEvt const * const e);
static QState QTTS_sleep(QTTS * const me, QEvt const * const e);
static QState QTTS_poweroff(QTTS * const me, QEvt const * const e);



/* Local objects -----------------------------------------------------------*/
static QTTS l_tts; /* the single instance of the Table active object */

/* Global-scope objects ----------------------------------------------------*/
QActive * const AO_TTS = &l_tts.super; /* "opaque" AO pointer */

/*..........................................................................*/
/* @(/1/30) ................................................................*/
void QTTS_ctor(void) {
    QTTS *me = &l_tts;
    QActive_ctor(&me->super, Q_STATE_CAST(&QTTS_initial));
}
/* @(/1/6) .................................................................*/
/* @(/1/6/0) ...............................................................*/
/* @(/1/6/0/0) */
static QState QTTS_initial(QTTS * const me, QEvt const * const e) {
    return Q_TRAN(&QTTS_poweroff);
}
/* @(/1/6/0/1) .............................................................*/
static QState QTTS_normal(QTTS * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* @(/1/6/0/1/0) */
        case TTS_READMSG_SIG: {
            status_ = Q_HANDLED();
            break;
        }
        /* @(/1/6/0/1/1) */
        case ACC_OFF_SIG: {
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/* @(/1/6/0/1/2) ...........................................................*/
static QState QTTS_idle(QTTS * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* @(/1/6/0/1/2/0) */
        case TTS_READMSG_SIG: {
            status_ = Q_TRAN(&QTTS_busy);
            break;
        }
        /* @(/1/6/0/1/2/1) */
        case ACC_OFF_SIG: {
            /* @(/1/6/0/1/2/1/0) */
            if (1) {
                status_ = Q_TRAN(&QTTS_sleep);
            }
            /* @(/1/6/0/1/2/1/1) */
            else if (0) {
                status_ = Q_HANDLED();
            }
            else {
                status_ = Q_UNHANDLED();
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&QTTS_normal);
            break;
        }
    }
    return status_;
}
/* @(/1/6/0/1/3) ...........................................................*/
static QState QTTS_busy(QTTS * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* @(/1/6/0/1/3/0) */
        case TTS_OK_SIG: {
            status_ = Q_TRAN(&QTTS_idle);
            break;
        }
        default: {
            status_ = Q_SUPER(&QTTS_normal);
            break;
        }
    }
    return status_;
}
/* @(/1/6/0/2) .............................................................*/
static QState QTTS_sleep(QTTS * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* @(/1/6/0/2/0) */
        case TTS_READMSG_SIG: {
            status_ = Q_TRAN(&QTTS_normal);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/* @(/1/6/0/3) .............................................................*/
static QState QTTS_poweroff(QTTS * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /* @(/1/6/0/3/0) */
        case Q_TIMEOUT_SIG: {
            status_ = Q_TRAN(&QTTS_normal);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

