/*****************************************************************************
* Model: bwgpsrecorder.qm
* File:  qmcode/qvideo.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/3/4) .................................................................*/
#include "qp_port.h"
#include "qevents.h"
#include "bsp.h"
#include "type.h"

Q_DEFINE_THIS_MODULE("qvideo.c")



/* Active object class -----------------------------------------------------*/
/* @(/1/3) .................................................................*/
typedef struct QVideoTag {
/* protected: */
    QActive super;
} QVideo;

/* protected: */
static QState QVideo_initial(QVideo * const me, QEvt const * const e);
static QState QVideo_state1(QVideo * const me, QEvt const * const e);



/* Local objects -----------------------------------------------------------*/
static QVideo l_Video; /* the single instance of the Table active object */

/* Global-scope objects ----------------------------------------------------*/
QActive * const AO_Video = &l_Video.super; /* "opaque" AO pointer */

/*..........................................................................*/
/* @(/1/25) ................................................................*/
void QVideo_ctor(void) {
    QVideo *me = &l_Video;
    QActive_ctor(&me->super, Q_STATE_CAST(&QVideo_initial));
}
/* @(/1/3) .................................................................*/
/* @(/1/3/0) ...............................................................*/
/* @(/1/3/0/0) */
static QState QVideo_initial(QVideo * const me, QEvt const * const e) {
    return Q_TRAN(&QVideo_state1);
}
/* @(/1/3/0/1) .............................................................*/
static QState QVideo_state1(QVideo * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

